import { SEND_STUDY_URL } from "@/lib/config";
import BentoCard from "../ui/BentoCard";
import Reveal from "../ui/Reveal";
import SpotlightGrid from "../ui/SpotlightGrid";
import { CheckArt, CleaningArt, DefenseArt, FindingsArt, ModelsArt, ProfilesArt, TestingArt } from "../ui/ServiceArt";
import { btnPrimary, container, heading, kicker, subtitle } from "../ui/styles";

export default function Services() {
  return (
    <section id="services" className="relative scroll-mt-16 py-16 lg:py-24">
      <div className={container}>
        <Reveal className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className={kicker}>Services</div>
            <h2 className={heading}>Every test your study needs</h2>
            <p className={subtitle}>From a quick data check to full structural models. Checked twice, explained simply.</p>
          </div>
          <a href={SEND_STUDY_URL} data-cta="services-send" className={`${btnPrimary} shrink-0`}>
            Send your study
          </a>
        </Reveal>

        <SpotlightGrid className="mt-10">
            <div data-h-scroll data-h-snap className="no-scrollbar flex snap-x snap-mandatory gap-px overflow-x-auto overscroll-x-contain rounded-[1px] sm:grid sm:grid-cols-2 sm:overflow-hidden lg:grid-cols-4">
            <BentoCard
              slide
              index="01"
              title="Data cleaning"
              desc="We flag answers that don't fit, check your data's shape, and confirm your survey is reliable before any test runs."
            >
              <CleaningArt />
            </BentoCard>

            <BentoCard
              slide
              index="02"
              title="Hypothesis testing"
              desc="The right test for your question, with effect sizes, not just p‑values."
              className="sm:order-first sm:col-span-2 lg:order-none"
              >
              <TestingArt />
            </BentoCard>

            <BentoCard
              slide
              index="03"
              title="APA tables and findings"
              desc="APA 7th edition, ready for Word, each with a plain-English note."
            >
              <FindingsArt />
            </BentoCard>

            <BentoCard
              slide
              index="04"
              title="Respondent profiles"
              desc="Who answered your survey, as frequency tables, charts, and cross-tabs."
            >
              <ProfilesArt />
            </BentoCard>

            <BentoCard
              slide
              index="05"
              title="Advanced models"
              desc="SEM and path models for dissertations, showing what affects what. Checked by a senior methodologist."
            >
              <ModelsArt />
            </BentoCard>

            <BentoCard
              slide
              index="06"
              title="Checked by two analysts"
              desc="Generated by our Statistical Analysts and independently audited by our Statistical Review Editors. We verify computational integrity, data hygiene, and APA compliance before certifying your results."
            >
              <CheckArt />
            </BentoCard>

            <BentoCard
              slide
              index="07"
              title="Defense prep"
              desc="A plain-English guide to the questions panels ask most, plus optional live practice."
            >
              <DefenseArt />
            </BentoCard>
          </div>
        </SpotlightGrid>
        <div className="mt-4 flex items-center justify-between gap-4 font-mono text-[11px] text-white/45 sm:justify-end">
          <span className="sm:hidden">Keep scrolling to see all 7</span>
          <span>Numbers shown are examples.</span>
        </div>
      </div>
    </section>
  );
}
